### ISSUE TITLE
Video splash seems to break the site on mobile

### ISSUE THREAD

**Issue by tintincastro** [hotdoy/grav-theme-hotdoy#18] opened 2020-03-21 10:24 UTC
Currently discovering Grav, I started fiddling with your theme (which looks super good on my desktop pc). I made a video splash similar to your live demo which works exactly as intended (still on my desktop pc), responsive and all.

But when I tried this on my smartphone, everything was broken (I'm using Firefox latest version on android/samsung). Only the title and the hamburger button showed and the whole website was covered by the splash background color. Only when I scroll, I sometimes see glimpses (maybe 5-10% of the viewport) of the content, and I can see that the video is running, so somewhere under this bug the site is there, but thats disappears as soon as the scroll stops.

At first, I thought it was me breaking everything, but I've got the exact same probleme on your live demo website hotdoy.ca (see screenshot below). You can scroll for a great distance, so I assume all your content is still there underneath the dark blue.

I suspect this has something to do with the way mobile device handles vh combined with the hidden overflow and the video, but currently, I'm not enough up to date on theses matters to come up with a fix.

Anyway, keep up the good work, because other than this problem, I love everything about your theme.

Hotdoy theme version : 1.7.12
Grav version : 1.6.23
Firefox mobile Screenshot :
![Screenshot_2020-03-21-10-53-11](https://user-images.githubusercontent.com/25725603/77224444-fbe24380-6b65-11ea-9966-98bd17dfc764.png)

**Comment by tintincastro** [comment] 2020-03-21 10:26
PS : I forgot to mention, the problem is the same with the chrome browser on my mobile.

**Comment by sebasvisser** [comment] 2020-04-13 14:14
Local hosted this seems to work. Even when switching to reponsive design mode.
However, hosted on a server (or going to that local server via Ngrok) the splash video breaks.
It is loaded.. at least partially, ngrok status says: 206 Partial Content
So basically not the whole video gets loaded or something.


After googling and searching for about an hour I get the idea that it's an feature, not a bug.

**Comment by sebasvisser** [comment] 2020-04-13 14:15
O0h snap! I found something..
we have to add the playsinline attribute!
At least, now it works on my iPhone

**Comment by sebasvisser** [comment] 2020-04-13 15:07
Ok to fix this:
file splash.html.twig
line 39: typo fixed:
`spalsh__media-ctn fill` to `splash__media-ctn fill`

line 76, add a new line for attribute playsinline:
`playsinline="1"`

I also added the attribute on line 86 after the loop attribute.

Dont know if it's all required. Just know it works now :)

**Comment by vincentrouleau** [comment] 2020-05-18 16:09
Ill make sure it's in the next patch. Thanks.

**Comment by vincentrouleau** [comment] 2020-05-20 19:55
Is it still an issue?

**Comment by vincentrouleau** [comment] 2020-05-31 20:32
I'll take that as good news.
Closing.

**Closed as completed by vincentrouleau** 2020-05-31 20:32 UTC
Labels: bug
