### ISSUE TITLE
"Back" doesn't work

### ISSUE THREAD

**Issue by jofemodo** [hotdoy/grav-theme-hotdoy#21] opened 2020-04-27 02:18 UTC
Browser's Back button doesn't work. It doesn't fail all the time, i'm trying to find a "pattern".

+ It seems to work correctly *ALWAYS" when returning to home. 
+ It fails "sometimes" when navigating using the menu or clicking internal links.

When it fails, the URL changes, and the contents are there, but they are hidden (you can copy/paste the text & images with the mouse). Only the footer is visible.

+ Reloading with F5, render the page normally.
+ Loading function is not being called.

Thanks

**Comment by jofemodo** [comment] 2020-04-27 03:07
It seems to be related with the "reveal-related" changes ...

**Comment by jofemodo** [comment] 2020-04-27 22:10
I found a kind of workaround for the issue by adding this fragment to loading.js:
```
window.addEventListener( "pageshow", function ( event ) {
	var historyTraversal = event.persisted || 
		( typeof window.performance != "undefined" && 
		window.performance.navigation.type === 2 );
	if ( historyTraversal ) {
		// Handle page restore.
		window.location.reload();
		$(window).scrollTop(0);
	}
});
```
I suspect that this is not a nice solution, so i would appreciate a nicer one ...

The best!

**Comment by pedro-poblete** [comment] 2020-05-14 16:47
This bug remains even when "Reveal Content" / Loading is disabled, so the problem is in another piece of javascript. Haven't been able to find it just yet.

As I don't load the loading.js file, I've added your workaround to site-header.js instead for now.

**Comment by jofemodo** [comment] 2020-05-14 22:59
Yes. It's difficult to catch ... and the workaround is far from ideal.  It causes some glitches and fake-reloads, specially on mobile. I hope @hotdoy find the problem ...

Regards ...

**Comment by vincentrouleau** [comment] 2020-05-15 12:39
A lot changed in the last weeks and I didn't had the time to check on the theme for a while. I don't even have a demo anymore. 
I'll set a new one up and check it out in the next days. 
Reveal and loading did change quite a lot. I'll update everything and push an update. 
Hopefully it fixes what you are talking about.

**Comment by vincentrouleau** [comment] 2020-05-15 14:30
**1.7.17 is out.**
Honestly, the browser back button thing is really weird since I don't really hack any behavior.
There are some "preventDefault" in the pagination and in forms ajax submission, but that's it.

If you are still experiencing this issue, check your console for any js error. 
If your projects are live, I could also go and take a look by myself.

**Comment by vincentrouleau** [comment] 2020-05-15 14:38
Think I got it. The link manager was an old version. I've updated it in 1.7.17.

**Comment by jofemodo** [comment] 2020-05-17 17:11
OK! I updated, removed my "workaround" and now it works.
Thanks a lot!!

**Comment by jofemodo** [comment] 2020-05-20 01:16
Hi @hotdoy !
Still not working fine. Take a luck here:

+ http://web2-GOOGLENOINDEX.zynthian.org

removing the "-GOOGLENOINDEX", of course ;-)

Try to navigate for all sections using the menu and going back.
From engines section, click an engine and then click "back" ...

Thanks!

**Comment by vincentrouleau** [comment] 2020-05-20 19:28
Alright sooo. When pressing the back button in Firefox, instead of reloading the last page, it looks like it's reloading a cached version of the last displayed page. Since I add the `exiting` class when leaving a page... Firefox brings it back, and the styles that goes with it (opacity 0).
I have completely removed this for now so the issue should be fixed but you will lose the fadeout when leaving a page. I will update if I find a nice way to do it without any bug.

This is in the v1.7.18 release.
You can also only update ```js/link.js``` if you modified the theme.

**Closed as completed** 2020-05-20 19:28 UTC

**Comment by jofemodo** [comment] 2020-05-21 10:02
It works nicely now. Thanks a lot for your effort, @hotdoy! I love your theme ;-)

BTW, still remains this problem:

https://github.com/hotdoy/grav-theme-hotdoy/issues/22

regards,
